# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Umami Kotlin
site_url: https://umami-kotlin.appoutlet.dev
repo_url: https://github.com/AppOutlet/umami-kotlin
repo_name: AppOutlet/umami-kotlin
theme:
  name: material
  palette:
    primary: 'deep purple'
    accent: 'indigo'
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.top
    - search.suggest
    - content.code.copy
    - content.tabs.link
  icon:
    logo: simple/simpleanalytics
    repo: fontawesome/brands/github

nav:
  - Overview: index.md
  - Getting started:
    - 🌎 Kotlin Multiplatform: getstarted/kmp.md
    - 🤖 Android: getstarted/android.md
  - Event tracking: event-tracking.md
  - Roadmap: roadmap.md
  - API Reference: reference

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

plugins:
  - search